fix: calling data from backend
osscameroon/onacut pull request #126
Opened 2022-08-08 11:47 UTC by yokwejuste

In relation to issue #119 This PR was raised.

2022-08-09 07:21 UTC, Zaker237 approved these changes

2022-08-10 07:18 UTC, Asam237 commented
@yokwejuste 
![Screenshot from 2022-08-10 08-17-16](https://user-images.githubusercontent.com/34966088/183839076-11f6e602-1934-44a5-b2d9-f84745a028d6.png)

2022-08-10 08:43 UTC, Sanix-Darker requested changes
Did you tested this pr ?

2022-08-10 09:04 UTC, yokwejuste commented
> Did you tested this pr ?

Yes Sanix! The PR where individually tested and running well.

2022-08-10 09:22 UTC, Asam237 requested changes

2022-08-10 09:22 UTC, Asam237 commented on frontend/src/pages/streetMap/StreetMap.page.tsx
>  import { LIST_QUARTIER } from "../../scripts/list_quartier";
Why does this file still exist?

2022-08-10 09:22 UTC, Asam237 commented on frontend/src/pages/streetMap/StreetMap.page.tsx
>                  {LIST_QUARTIER.map((item: any, index: any) => (
Remove all constant files

2022-08-10 09:28 UTC, yokwejuste commented on frontend/src/pages/streetMap/StreetMap.page.tsx
>  import { LIST_QUARTIER } from "../../scripts/list_quartier";
Please! An issue surely with the management of my branches. Le tme make an update

2022-08-11 05:02 UTC, Asam237 approved these changes

2022-08-11 05:03 UTC, merged