Init the Backend app with FastAip
osscameroon/onacut pull request #138
Opened 2022-10-10 16:30 UTC by Zaker237

Features:
- app structure
- most of needed files
- database config
- SQLAlchemy database file
- all module(alert, city, region, distict)
---

2022-10-10 19:49 UTC, yokwejuste reviewed
Some changes might be needed here I think

2022-10-10 19:49 UTC, yokwejuste commented on fastapi/onacut/schemas/region.py
> +    name: str
```suggestion
    name: str
    total_alerts: int
```

2022-10-10 19:49 UTC, yokwejuste commented on fastapi/onacut/schemas/region.py
> +    name: str
Actually the /list page is showing the regions together with their id, to ease the work for the frontend devs, we need to consider adding the total_alert field

2022-10-10 19:49 UTC, yokwejuste commented on fastapi/onacut/schemas/alert.py
> +
```suggestion
from pydantic_choices import choice
```

2022-10-10 19:49 UTC, yokwejuste commented on fastapi/onacut/schemas/alert.py
> +
In pydantic the choices are implemented already, getting the type of alerts as str might be bad cause we might something different coming in the JSON

2022-10-10 19:49 UTC, yokwejuste commented on fastapi/onacut/schemas/alert.py
> +    type: str
```suggestion
    type: choice(["electricity", "water", "internet"])
```

2022-10-10 19:49 UTC, yokwejuste commented on fastapi/onacut/schemas/alert.py
> +    type: str
Reference: https://pypi.org/project/pydantic-choices/

2022-10-10 23:46 UTC, Zaker237 commented
@yokwejuste  you can check it again. the schemas shoulds be rewrite but i thing changing it in another PR will be a good idea. the Pr is already big but he setup fast all needs for the backend with fastapi

2022-10-11 21:27 UTC, jefcolbi requested changes
Please see the comments i left

2022-10-11 21:27 UTC, jefcolbi commented on fastapi/onacut/routers/alerts.py
> +    data = db.query(AlertModel).all()
calling a sync function inside an async function degrade the performance of asynchronicity.
not sure but this can help convert the sync calls to async
https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html

2022-10-11 21:27 UTC, jefcolbi commented on fastapi/onacut/tests/test_alerts.py
> +
to tests it is not better to create the model entries first, then call the endpoint and check that the data returned is the entries we created.

2022-10-11 21:41 UTC, Zaker237 commented on fastapi/onacut/tests/test_alerts.py
> +
sure all there tests will be rewrite. for This fits PR the focus was on the Architecture of the new App.

2022-10-13 00:20 UTC, merged