update: - The language change button has been updated in terms of UX …
osscameroon/onacut pull request #142
Opened 2022-10-15 11:58 UTC by mouafus

- [x] The language change button has been updated in terms of UX and positioning on the homepage and in the drawer
- [x] Changing the page from the drawer no longer refreshes the browser tab;
- [x] page 'add-report', we can now open the drawer without any chance of getting the "Cannot POST /add-alert" error
- [x] error during the build of the "report" icon which was not loaded fixed
- [x]  Translation of drawer contents, add-report page and other contents

2022-10-15 20:53 UTC, Asam237 requested changes

2022-10-15 20:53 UTC, Asam237 commented on frontend/src/components/drawer/Drawer.component.tsx
> +        console.log("problem herer");
Remove the console.log

2022-10-15 20:56 UTC, Asam237 commented
Great work @mouafus

2022-10-17 22:00 UTC, mouafus commented on frontend/src/components/drawer/Drawer.component.tsx
> +        console.log("problem herer");
Done

2022-10-17 22:04 UTC, mouafus reviewed
I removed that `console.log`

2022-10-18 08:44 UTC, Asam237 approved these changes

2022-10-18 08:45 UTC, merged