Add new fields on AlertSchema
osscameroon/onacut pull request #168
Opened 2022-11-21 03:14 UTC by Zaker237

WHAT:
this PR add the fields, region, city and district on AlertSchema on POST and GET

WHY:
to match the old backend and avoid a big refactor on the frontend

2022-11-23 08:07 UTC, Sanix-Darker requested changes
Thanks for this amazing PR, i left some remarks and comments !

2022-11-23 08:07 UTC, Sanix-Darker commented on fastapi/onacut/schemas/alert.py
> +    district: str
For what i can see in the database definition of alert... these fields should be integer... ? 🤔  Or am missing something ?

```sql
CREATE TABLE alert (
    .
    .
    .
    region_id INTEGER,
    city_id INTEGER,
    district_id INTEGER,
    PRIMARY KEY (id),
    FOREIGN KEY(region_id) REFERENCES region (id),
    FOREIGN KEY(city_id) REFERENCES city (id),
    FOREIGN KEY(district_id) REFERENCES district (id)
);
```

2022-11-23 08:07 UTC, Sanix-Darker commented on fastapi/onacut/routers/alerts.py
> +    return db_alert.to_dict()
jsonable_encoder... ?

2022-11-23 08:07 UTC, Sanix-Darker commented on fastapi/onacut/routers/alerts.py
> +        alerts = alerts.filter_by(district_id=int(district))
- types definition are either str or None... but, we're accessing in the implementation atributes ? 🤔  am confused.. if region is a string for ex "Nord", can we really get something from `"Nord".id` 
- i think we can define integers direcly from the method definition itself instead of casting on each elements
- and checking only the variable should be enough right ? 🤔  no need of the `len(....) > 1`


What do you think ?

2022-11-23 08:07 UTC, Sanix-Darker commented on fastapi/onacut/routers/regions.py
> +    "",
is there a reason for this change please ? 🙏🏽  just curious !

2022-11-23 14:58 UTC, Zaker237 commented on fastapi/onacut/models.py
> +
yes 
i did it

2022-11-23 15:02 UTC, Zaker237 commented on fastapi/onacut/routers/regions.py
> +    "",
this route should allows parameters and i also wanted to really match the old backend. 

the idea behind is to avoid as most as possible a big refacto on the frontend

2022-11-23 15:08 UTC, Zaker237 commented on fastapi/onacut/routers/alerts.py
> +    return db_alert.to_dict()
could be a good idea but i'm not sure if it's suitable for the case. we can discuss it later in a call

2022-11-23 15:35 UTC, Sanix-Darker commented
And yeah, also, i forgot to tell this but, we don't want to version/track changes made in the test Database, please can you remove it from all changes on this PR ? 🙏🏽 
I should have mentioned it sorry about that !

2022-11-23 15:37 UTC, Zaker237 commented
It's okay i will do it

2022-11-25 11:35 UTC, Zaker237 commented on fastapi/onacut/routers/alerts.py
> +    if region and len(region) > 1:
Hey @Sanix-Darker, as you ca see hier i updated the Code.

the idea behind it is the followindǵ:

- In the table alert. the region, the district and the city are Foreingkeys and those are then integer with reference.
- It is difficult in frontend to know the id of the element(region, city or district) we want to filter on.
- as solution a then allows user to give the name as string and the use that name to first find the element and then use its id to filter alerts

An alternative can be to first make a request to get for example city id base on it name and then use that id to filter alerts.....

let me know if you get the point. 
i'm also open to suggestion

2022-11-29 06:17 UTC, Sanix-Darker approved these changes

2022-11-29 06:23 UTC, merged